# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
# benchmarks:
#   rlang-benchmarks:
#     dependencies:
#     - base
#     - rlang
#     - criterion
#     ghc-options:
#     - -rtsopts
#     - -threaded
#     - -with-rtsopts=-N
#     main: Main.hs
#     source-dirs: benchmark
category: Other
description: rlang is a new Haskeleton package.
executables:
  rlang:
    dependencies:
    - base
    - rlang
    - text >= 1.2.2.0
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: robinvd/rlang
library:
  dependencies:
  - base
  - parsec
    # - parsec-numbers
  - containers >= 0.5.5
  - mtl >= 2.2.1
  - text >= 1.2.2.0
  - bytestring >= 0.10.8.1
  source-dirs: library
license: MIT
maintainer: Robin
name: rlang
synopsis: A new Haskeleton package.
# tests:
#   rlang-test-suite:
#     dependencies:
#     - base
#     - rlang
#     - tasty
#     - tasty-hspec
#     ghc-options:
#     - -rtsopts
#     - -threaded
#     - -with-rtsopts=-N
#     main: Main.hs
#     source-dirs: test-suite
version: '0.0.0'
